Update install-cmdstan.yaml

diff --git a/.github/workflows/install-cmdstan.yaml b/.github/workflows/install-cmdstan.yaml
--- a/.github/workflows/install-cmdstan.yaml
+++ b/.github/workflows/install-cmdstan.yaml
@@ -21,41 +21,45 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Determine Number of Cores
-      id: set-cores
+    - name: Determine Number of Cores (Unix)
+      if: runner.os != 'Windows'
       run: |
-        if ($env:RUNNER_OS -eq "Windows") {
-          $numCores = [Environment]::ProcessorCount
-          echo "NUM_CORES=$numCores" | Out-File -Append -FilePath $env:GITHUB_ENV
-        } else {
-          numCores=$(nproc)
-          echo "NUM_CORES=$numCores" >> $GITHUB_ENV
-        }
-      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
+        numCores=$(nproc)
+        echo "NUM_CORES=$numCores" >> $GITHUB_ENV
+      shell: bash
+
+    - name: Determine Number of Cores (Windows)
+      if: runner.os == 'Windows'
+      run: |
+        $numCores = [Environment]::ProcessorCount
+        echo "NUM_CORES=$numCores" | Out-File -Append -FilePath $env:GITHUB_ENV
+      shell: pwsh
 
     - name: Install CmdStan
       uses: epinowcast/actions/install-cmdstan@main
       with:
         cmdstan-version: 'latest'
     
-    - name: Validate Installation
+    - name: Validate Installation (Unix)
+      if: runner.os != 'Windows'
       run: |
-        if ($env:RUNNER_OS -eq "Windows") {
-          Write-Host "CmdStan installed in: $env:CMDSTAN_PATH"
-          if (Test-Path -Path $env:CMDSTAN_PATH) {
-            Write-Host "CmdStan directory found."
-          } else {
-            Write-Host "CmdStan directory not found."
-            exit 1
-          }
-        } else {
-          echo "CmdStan installed in: ${CMDSTAN_PATH}"
-          if [ -d "${CMDSTAN_PATH}" ]; then
-            echo "CmdStan directory found."
-          else
-            echo "CmdStan directory not found."
-            exit 1
-          fi
-        }
-      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
+        echo "CmdStan installed in: ${CMDSTAN_PATH}"
+        if [ -d "${CMDSTAN_PATH}" ]; then
+          echo "CmdStan directory found."
+        else
+          echo "CmdStan directory not found."
+          exit 1
+        fi
+      shell: bash
 
+    - name: Validate Installation (Windows)
+      if: runner.os == 'Windows'
+      run: |
+        Write-Host "CmdStan installed in: $env:CMDSTAN_PATH"
+        if (Test-Path -Path $env:CMDSTAN_PATH) {
+          Write-Host "CmdStan directory found."
+        } else {
+          Write-Host "CmdStan directory not found."
+          exit 1
+        }
+      shell: pwsh
